name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Build with Maven
      run: | 
        mvn -B package --file pom.xml
        mvn test -B package --file pom.xml
    - uses: Azure/docker-login@v1
      with:
        login-server: docker.pkg.github.com
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }} 
    - name: Push Docker image
      run: |
        docker build -t webgoat/webgoat-8.0 webgoat-server
        docker tag webgoat/webgoat-8.0 docker.pkg.github.com/bas/webgoat/webgoat-8.0:${{ github.sha }}
        docker push docker.pkg.github.com/bas/webgoat/webgoat-8.0:${{ github.sha }}
