name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    
    - uses: Azure/docker-login@v1
      with:
        login-server: docker.pkg.github.com
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }} 
    
    - name: Docker build
      run: |
        docker build -t webgoat/webgoat-8.0 webgoat-server
      
    - name: Run the Anchore scan action itself with GitHub Advanced Security code scanning integration enabled
      uses: anchore/scan-action@main
      with:
        image: "webgoat/webgoat-8.0"
        acs-report-enable: true

    - name: Upload Anchore Scan Report
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: results.sarif
   
    - name: Docker push
      run: |
        docker tag webgoat/webgoat-8.0 docker.pkg.github.com/bas/webgoat/webgoat-8.0:${{ github.sha }}
        docker push docker.pkg.github.com/bas/webgoat/webgoat-8.0:${{ github.sha }}
